apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-starter-reactjs
  labels:
    app: gke-starter-reactjs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-starter-reactjs
  template:
    metadata:
      labels:
        app: gke-starter-reactjs
    spec:
      containers:
      - name: gke-starter-reactjs
        image: <IMAGE_PLACEHOLDER>
        ports:
        - containerPort: 80
